name: Continuous Integration

on:
  push:
  pull_request:
    branches: [ bleed, 'prep-*' ]

permissions:
  contents: read  #  to fetch code (actions/checkout)

jobs:
  linux:
    name: Linux (.NET 6.0)
    runs-on: ubuntu-22.04

    steps:
      - name: Remove System .NET
        run: sudo apt-get remove -y dotnet*

      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Install .NET 6.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      - name: Check Code
        run: |
          make check
          make tests

      - name: Check Mods
        run: |
          sudo apt-get install lua5.1
          make check-scripts
          make TREAT_WARNINGS_AS_ERRORS=true test
